mu-node-manage: gracefully try WinRM to do things, then fail to ssh if it doesn't work

diff --git a/bin/mu-node-manage b/bin/mu-node-manage
--- a/bin/mu-node-manage
+++ b/bin/mu-node-manage
@@ -215,12 +215,30 @@ def runCommand(deploys = MU::MommaCat.listDeploys, nodes = [], cmd = "( chef-cli
         begin
           MU.log "Running #{cmd} on #{nodename} (##{count})" if !print_output
           serverobj = mommacat.findLitterMate(type: "server", mu_name: nodename)
+          output = nil
+          exitcode = -1
           if serverobj.windows?
-            serverobj.groomer.run(max_retries: 0, output: print_output)
+            resp = nil
+            begin
+              shell = serverobj.getWinRMSession(0, timeout: 10, winrm_retries: 1)
+              resp = shell.run("ipconfig /all")
+              pp resp
+            rescue MU::MuError => e
+            end
+            if !resp or resp.exitcode != 0
+              MU.log "WinRM connection to #{nodename} failed, trying SSH", MU::WARN
+            else
+              output = resp.stdout
+              exitcode = resp.exitcode
+            end
           end
-          output=`ssh -q #{nodename} "#{cmd}" 2>&1 < /dev/null`
-          if !$?.success?
-            if server['conf']["platform"] == "windows" and output.match(/NoMethodError: unknown property or method: `ConnectServer'/)
+          if !output
+            # maybe this should use getSSHSession, for the sake of symmetry
+            output = `ssh -q #{nodename} "#{cmd}" 2>&1 < /dev/null`
+            exitcode = $?.exitstatus
+          end
+          if exitcode != 0
+            if serverobj.windows? and output.match(/NoMethodError: unknown property or method: `ConnectServer'/)
               MU.log "#{nodename} encountered transient Windows/Chef ConnectServer error, retrying", MU::WARN
             elsif print_output
               done = true
@@ -230,8 +248,9 @@ def runCommand(deploys = MU::MommaCat.listDeploys, nodes = [], cmd = "( chef-cli
               done = true
               MU.log "#{nodename} did not exit cleanly", MU::WARN, details: output.slice(-2000, 2000)
             end
-            exit $?.exitstatus if done
+            exit exitcode if done
           else
+            MU.log "#{nodename} complete"
             done = true
           end
         end until done
